config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "achievers#index"

  resources :achievers
  resources :habits
  resources :achiever_habits

  resources :book_recommendations
  resources :achiever_book_recommendations

  resources :quotes

end

app/models/achiever.rb
class Achiever < ApplicationRecord	
	has_many :achiever_habits, dependent: :destroy
	has_many :habits, through: :achiever_habits, dependent: :destroy

	has_many :achiever_book_recommendations, dependent: :destroy
	has_many :book_recommendations, through: :achiever_book_recommendations

	has_many :quotes, dependent: :destroy
	belongs_to :user

	validates :name, :area_of_expertise, presence: true

end

app/controllers/achievers_controller.rb
class AchieversController < ApplicationController
  before_action :set_achiever, only: %i[ show edit update destroy ]

  # GET /achievers or /achievers.json
  def index
    @achievers = Achiever.all
  end

  # GET /achievers/1 or /achievers/1.json
  def show
  end

  # GET /achievers/new
  def new
    @achiever = Achiever.new
  end

  # GET /achievers/1/edit
  def edit
  end

  # POST /achievers or /achievers.json
  def create
    # by adding 'current_user.controller_in_plural', the user id gets auto-assigned.
    @achiever = current_user.achievers.new(achiever_params)

    respond_to do |format|
      if @achiever.save
        format.html { redirect_to achiever_url(@achiever), notice: "Achiever was successfully created." }
        format.json { render :show, status: :created, location: @achiever }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @achiever.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /achievers/1 or /achievers/1.json
  def update
    respond_to do |format|
      if @achiever.update(achiever_params)
        format.html { redirect_to achiever_url(@achiever), notice: "Achiever was successfully updated." }
        format.json { render :show, status: :ok, location: @achiever }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @achiever.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /achievers/1 or /achievers/1.json
  def destroy
    @achiever.destroy

    respond_to do |format|
      format.html { redirect_to achievers_url, notice: "Achiever was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_achiever
      @achiever = Achiever.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def achiever_params
      params.require(:achiever).permit(:name, :area_of_expertise)
    end
end

app/helpers/achievers_helper.rb
module AchieversHelper
end

app/views/achievers/_achiever.html.erb
<div id="<%= dom_id achiever %>">

      <tr>
        <td>
          <%= link_to achiever.name, achiever %>
        </td>
        <td>
          <%= achiever.area_of_expertise %></td>
        <td>
          <% achiever.habits.each do |habit| %>
            <%= link_to habit.name, habit %><br>
          <% end %>
        </td>

        <td>
          <% achiever.book_recommendations.each do |book_recommendation| %>
            <%= link_to book_recommendation.title, book_recommendation %><br>
          <% end %>
        </td>

        <td>
          <% achiever.quotes.each do |quote| %>
            <%= link_to quote.text, quote %><br><br>
          <% end %>
        </td>

      </td>

    </tr>

</div>

app/views/achievers/_form.html.erb
<%= form_with(model: achiever) do |form| %>
<% if achiever.errors.any? %>
  <div id="error_explanation" style="color: red">
    <h2><%= pluralize(achiever.errors.count, "error") %>
      prohibited this achiever from being saved:</h2>

    <ul>
      <% achiever.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field form-group">
  <%= form.label :name, style: "display: block" %>
  <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
</div>

<div class="field form-group">
  <%= form.label :area_of_expertise, style: "display: block" %>
  <%= form.text_field :area_of_expertise, class:"form-control", placeholder:"Area of expertise" %>
</div>

<div class="actions">
  <%= form.submit class:'btn btn-secondary'%>
</div>
<% end %>

app/views/achievers/_table_footer.html.erb
    </tbody>
  </table>

app/views/achievers/_table_header.html.erb
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr class="sticky-top">
        <th>Name</th>
        <th>Area of expertise</th>
        <th>Habits</th>
        <th>Book recommendations</th>
        <th>Quotes</th>
      </tr>
    </thead>

    <tbody>

app/views/achievers/edit.html.erb
<h1>Editing achiever</h1>

<%= render "form", achiever: @achiever %>

<br>

<div>
  <%= link_to "Show this achiever", @achiever, class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp

  <%= link_to "Back to achievers", achievers_path, class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp
</div>

app/views/achievers/index.html.erb
<h1>Achievers
  <% if user_signed_in? %>
    <%= link_to "Add achiever", new_achiever_path, class:'btn btn-secondary', style:'float: right; line-height: 200%;' %>
  <% end %>
</h1>

<%= render "table_header" %>

  <% @achievers.each do |achiever| %>
    <%= render achiever %>
  <% end %>
    
<%= render "table_footer" %>

</div>

app/views/achievers/new.html.erb
<h1>New achiever</h1>

<%= render "form", achiever: @achiever %>

<br>

<div>
  <%= link_to "Back to achievers", achievers_path, class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>
</div>

app/views/achievers/show.html.erb
<%= render "table_header" %>

<%= render @achiever %>

<%= render "table_footer" %>

<div>

  <% if user_signed_in? && current_user.id == 1 || user_signed_in? && current_user.id == @achiever.user_id %>

    <%= link_to "Edit this achiever", edit_achiever_path(@achiever), class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp

  <% end %>


  <%= link_to "Back to achievers", achievers_path, class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp


  <% if user_signed_in? && current_user.id == 1 || user_signed_in? && current_user.id == @achiever.user_id %>

    <%= button_to "Destroy this achiever", @achiever, method: :delete, class:'btn btn-danger', style:'margin-top:1%; margin-bottom: 1%' %>

  <% end %>


  <% if user_signed_in? %>

    <%= link_to "Add habit", new_habit_path, class:'btn btn-success', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp

    <%= link_to "Add book recommendation", new_book_recommendation_path, class:'btn btn-warning', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp

    <%= link_to "Add quote", new_quote_path, class:'btn btn-info', style:'margin-top:1%; margin-bottom: 1%' %>

  <% end %>

</div>