config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "achievers#index"

  resources :achievers
  resources :habits
  resources :achiever_habits

  resources :book_recommendations
  resources :achiever_book_recommendations

  resources :quotes

end

app/models/book_recommendation.rb
class BookRecommendation < ApplicationRecord
	has_many :achiever_book_recommendations, dependent: :destroy
	has_many :achievers, through: :achiever_book_recommendations
	belongs_to :user

	accepts_nested_attributes_for :achiever_book_recommendations

	validates :title, :author, presence: true
	validates_associated :achiever_book_recommendations
end

app/controllers/book_recommendations_controller.rb
class BookRecommendationsController < ApplicationController
  before_action :set_book_recommendation, only: %i[ show edit update destroy ]

  # GET /book_recommendations or /book_recommendations.json
  def index
    @book_recommendations = BookRecommendation.all
  end

  # GET /book_recommendations/1 or /book_recommendations/1.json
  def show
  end

  # GET /book_recommendations/new
  def new
    @book_recommendation = BookRecommendation.new
    # nested model:
    @book_recommendation.achiever_book_recommendations.new

  end

  # GET /book_recommendations/1/edit
  def edit
  end

  # POST /book_recommendations or /book_recommendations.json
  def create
    # by adding 'current_user.controller_in_plural', the user id gets auto-assigned.
    @book_recommendation = current_user.book_recommendations.new(book_recommendation_params)

    respond_to do |format|
      if @book_recommendation.save
        format.html { redirect_to book_recommendation_url(@book_recommendation), notice: "Book recommendation was successfully created." }
        format.json { render :show, status: :created, location: @book_recommendation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_recommendations/1 or /book_recommendations/1.json
  def update
    respond_to do |format|
      if @book_recommendation.update(book_recommendation_params)
        format.html { redirect_to book_recommendation_url(@book_recommendation), notice: "Book recommendation was successfully updated." }
        format.json { render :show, status: :ok, location: @book_recommendation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_recommendations/1 or /book_recommendations/1.json
  def destroy
    @book_recommendation.destroy

    respond_to do |format|
      format.html { redirect_to book_recommendations_url, notice: "Book recommendation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_recommendation
      @book_recommendation = BookRecommendation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_recommendation_params
      # and to get data from nested form "achiever_book_recommendations_attributes":
      params.require(:book_recommendation).permit(:title, :author, achiever_book_recommendations_attributes: [:achiever_id])
    end
end

app/helpers/book_recommendations_helper.rb
module BookRecommendationsHelper
end

app/views/book_recommendations/_book_recommendation.html.erb
<div id="<%= dom_id book_recommendation %>">

      <tr>
        <td>
          <%= link_to book_recommendation.title, book_recommendation %>
        </td>
        <td>
          <%= book_recommendation.author %></td>

        <td>
          <% book_recommendation.achievers.each do |achiever| %>
            <%= link_to achiever.name, achiever %><br>
          <% end %>
        </td>

      </td>

    </tr>

</div>

app/views/book_recommendations/_form_edit.html.erb
<%= form_with(model: book_recommendation) do |form| %>
<% if book_recommendation.errors.any? %>
  <div id="error_explanation" style="color: red">
    <h2><%= pluralize(book_recommendation.errors.count, "error") %>
      prohibited this book_recommendation from being saved:</h2>

    <ul>
      <% book_recommendation.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field form-group">
  <%= form.label :title, style: "display: block" %>
  <%= form.text_field :title, class:"form-control", placeholder:"Title" %>
</div>

<div class="field form-group">
  <%= form.label :author, style: "display: block" %>
  <%= form.text_field :author, class:"form-control", placeholder:"Author" %>
</div>

<div class="actions">
<%= form.submit class:'btn btn-secondary'%>
</div>
<% end %>

app/views/book_recommendations/_form_new.html.erb
<%= form_with(model: book_recommendation) do |form| %>
<% if book_recommendation.errors.any? %>
  <div id="error_explanation" style="color: red">
    <h2><%= pluralize(book_recommendation.errors.count, "error") %>
      prohibited this book_recommendation from being saved:</h2>

    <ul>
      <% book_recommendation.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field form-group">
  <%= form.label :title, style: "display: block" %>
  <%= form.text_field :title, class:"form-control", placeholder:"Title" %>
</div>

<div class="field form-group">
  <%= form.label :author, style: "display: block" %>
  <%= form.text_field :author, class:"form-control", placeholder:"Author" %>
</div>

<%= form.fields_for :achiever_book_recommendations do |child_form| %>
<div class="field form-group">
  <%= child_form.label :achiever_id, style: "display: block" %>
  <%= child_form.collection_select :achiever_id, Achiever.order(:name),:id,:name, include_blank: true %>
</div>
<% end %>

<div class="actions">
<%= form.submit class:'btn btn-secondary'%>
</div>
<% end %>

app/views/book_recommendations/_table_footer.html.erb
    </tbody>
   </table>

app/views/book_recommendations/_table_header.html.erb
 <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr class="sticky-top">
        <th>Title</th>
        <th>Author</th>
        <th>Achievers</th>
      </tr>
    </thead>

    <tbody>

app/views/book_recommendations/edit.html.erb
<h1>Editing book recommendation</h1>

<%= render "form_edit", book_recommendation: @book_recommendation %>

<br>

<div>
  <%= link_to "Show this book recommendation", @book_recommendation, class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp

  <%= link_to "Back to book recommendations", book_recommendations_path, class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp

</div>

app/views/book_recommendations/index.html.erb
<h1>Book recommendations
  <% if user_signed_in? %>

    <%= link_to "Add new book recommendation", new_book_recommendation_path, class:'btn btn-secondary', style:'float: right; line-height: 200%;' %>

  <% end %>

</h1>

<div id="book_recommendations">

<%= render "table_header" %>

  <% @book_recommendations.each do |book_recommendation| %>
    <%= render book_recommendation %>
  <% end %>

<%= render "table_footer" %>

</div>

app/views/book_recommendations/new.html.erb
<h1>New book recommendation</h1>

<%= render "form_new", book_recommendation: @book_recommendation %>

<br>

<div>
    <%= link_to "Back to book recommendations", book_recommendations_path, class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp
</div>

app/views/book_recommendations/show.html.erb
<%= render "table_header" %>

<%= render @book_recommendation %>

<%= render "table_footer" %>

<div>

    <% if user_signed_in? && current_user.id == 1 || user_signed_in? && current_user.id == @book_recommendation.user_id %>

      <%= link_to "Edit this book recommendation", edit_book_recommendation_path(@book_recommendation), class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp

    <% end %>


    <%= link_to "Back to book recommendations", book_recommendations_path, class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp


    <% if user_signed_in? && current_user.id == 1 || user_signed_in? && current_user.id == @book_recommendation.user_id %>

      <%= button_to "Destroy this book recommendation", @book_recommendation, method: :delete, class:'btn btn-danger', style:'margin-top:1%; margin-bottom: 1%' %>

    <% end %>

    <% if user_signed_in? %>

      <%= link_to "Add achiever to the book recommendation", new_achiever_book_recommendation_path, class:'btn btn-warning', style:'margin-top:1%; margin-bottom: 1%' %>

    <% end %>

</div>