config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "achievers#index"

  resources :achievers
  resources :habits
  resources :achiever_habits

  resources :book_recommendations
  resources :achiever_book_recommendations

  resources :quotes

end

app/models/habit.rb
class Habit < ApplicationRecord
	has_many :achiever_habits, dependent: :destroy
	has_many :achievers, through: :achiever_habits
	belongs_to :user

	accepts_nested_attributes_for :achiever_habits

	validates :name, :frequency, :time_demand, presence: true
	validates_associated :achiever_habits
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: %i[ show edit update destroy ]

  # GET /habits or /habits.json
  def index
    @habits = Habit.all
  end

  # GET /habits/1 or /habits/1.json
  def show
  end

  # GET /habits/new
  def new
    @habit = Habit.new
    # nested model:
    @habit.achiever_habits.new
  end

  # GET /habits/1/edit
  def edit
  end

  # POST /habits or /habits.json
  def create
    # by adding 'current_user.controller_in_plural', the user id gets auto-assigned.
    @habit = current_user.habits.new(habit_params)

    respond_to do |format|
      if @habit.save
        format.html { redirect_to habit_url(@habit), notice: "Habit was successfully created." }
        format.json { render :show, status: :created, location: @habit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /habits/1 or /habits/1.json
  def update
    respond_to do |format|
      if @habit.update(habit_params)
        format.html { redirect_to habit_url(@habit), notice: "Habit was successfully updated." }
        format.json { render :show, status: :ok, location: @habit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habits/1 or /habits/1.json
  def destroy
    @habit.destroy

    respond_to do |format|
      format.html { redirect_to habits_url, notice: "Habit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habit
      @habit = Habit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def habit_params
      # and to get data from nested form "achiever_habits_attributes":
      params.require(:habit).permit(:name, :frequency, :time_demand, achiever_habits_attributes: [:achiever_id])
    end
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/views/habits/_form_edit.html.erb
<%= form_with(model: habit) do |form| %>
<% if habit.errors.any? %>
  <div id="error_explanation" style="color: red">
    <h2><%= pluralize(habit.errors.count, "error") %>
      prohibited this habit from being saved:</h2>

    <ul>
      <% habit.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field form-group">
  <%= form.label :name, style: "display: block" %>
  <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
</div>

<div class="field form-group">
  <%= form.label :frequency, style: "display: block" %>
  <%= form.text_field :frequency, class:"form-control", placeholder:"Frequency" %>
</div>

<div class="field form-group">
  <%= form.label :time_demand, style: "display: block" %>
  <%= form.text_field :time_demand, class:"form-control", placeholder:"Time demand" %>
</div>

<div class="actions">
<%= form.submit class:'btn btn-secondary'%>
</div>

<% end %>

app/views/habits/_form_new.html.erb
<%= form_with(model: habit) do |form| %>
<% if habit.errors.any? %>
  <div id="error_explanation" style="color: red">
    <h2><%= pluralize(habit.errors.count, "error") %>
      prohibited this habit from being saved:</h2>

    <ul>
      <% habit.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field form-group">
  <%= form.label :name, style: "display: block" %>
  <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
</div>

<div class="field form-group">
  <%= form.label :frequency, style: "display: block" %>
  <%= form.text_field :frequency, class:"form-control", placeholder:"Frequency" %>
</div>

<div class="field form-group">
  <%= form.label :time_demand, style: "display: block" %>
  <%= form.text_field :time_demand, class:"form-control", placeholder:"Time demand" %>
</div>

<%= form.fields_for :achiever_habits do |child_form| %>
<div class="field form-group">
  <%= child_form.label :achiever_id, style: "display: block" %>
  <%= child_form.collection_select :achiever_id, Achiever.order(:name),:id,:name, include_blank: true %>
</div>

<% end %>

<div class="actions">
<%= form.submit class:'btn btn-secondary'%>
</div>

<% end %>

app/views/habits/_habit.html.erb
<div id="<%= dom_id habit %>">

      <tr>
        <td>
          <%= link_to habit.name, habit %>
        </td>
        <td>
          <%= habit.frequency %></td>
        <td>
          <%= habit.time_demand %></td>

        <td>
          <% habit.achievers.each do |achiever| %>
            <%= link_to achiever.name, achiever %><br>
          <% end %>
        </td>

      </td>

    </tr>

</div>

app/views/habits/_table_footer.html.erb
    </tbody>
 </table>

app/views/habits/_table_header.html.erb
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr class="sticky-top">
        <th>Name</th>
        <th>Frequency</th>
        <th>Time demand</th>
        <th width="25">Achievers</th>
      </tr>
    </thead>

    <tbody>

app/views/habits/edit.html.erb
<h1>Editing habit</h1>

<%= render "form_edit", habit: @habit %>

<br>

<div>
  <%= link_to "Show this habit", @habit, class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp

  <%= link_to "Back to habits", habits_path, class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp
</div>

app/views/habits/index.html.erb
<h1>Habits
  <% if user_signed_in? %>

    <%= link_to "Add habit", new_habit_path, class:'btn btn-secondary', style:'float: right; line-height: 200%;' %>
  <% end %>
</h1>

<div id="habits">
  
  <%= render "table_header" %>

  <% @habits.each do |habit| %>
    <%= render habit %>
  <% end %>

  <%= render "table_footer" %>

</div>

app/views/habits/new.html.erb
<h1>New habit</h1>

<%= render "form_new", habit: @habit %>

<br>

<div>
  <%= link_to "Back to habits", habits_path, class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp
</div>

app/views/habits/show.html.erb
<%= render "table_header" %>

<%= render @habit %>

<%= render "table_footer" %>

<div>

  <% if user_signed_in? && current_user.id == 1 || user_signed_in? && current_user.id == @habit.user_id %>

    <%= link_to "Edit this habit", edit_habit_path(@habit), class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp

  <% end %>


  <%= link_to "Back to habits", habits_path, class:'btn btn-light', style:'margin-top:1%; margin-bottom: 1%' %>&nbsp


  <% if user_signed_in? && current_user.id == 1 || user_signed_in? && current_user.id == @habit.user_id %>

  <%= button_to "Destroy this habit", @habit, method: :delete, class:'btn btn-danger', style:'margin-top:1%; margin-bottom: 1%' %>

  <% end %>

    <% if user_signed_in? %>

    <%= link_to "Add achiever to the habit", new_achiever_habit_path, class:'btn btn-success', style:'margin-top:1%; margin-bottom: 1%' %>

  <% end %>

</div>